### ISSUE TITLE
Добавить ссылку на демо страницы

### ISSUE THREAD

**Issue by tsvetkovamaria** [AlexandraFetisova/html-group_8-homework_34_alexandra#10]
Для облегчения просмотра вашей страницы, было бы здорово добавить сылку на уже свертсанную страницу (демо) в файл readme.md вашего репозитория. Тогда любой человек сможет зайтив репо, кликнуть на ссылку и посмотреть готовую работу в браузере, не клонируя репо локально. 

Можно добавить себе демо версию страницы через github pages

**Comment by AlexandraFetisova** [comment]
Ссылка добавлена https://alexandrafetisova.github.io/html-group_8-homework_34_alexandra/.
