### ISSUE TITLE
Страница скроллится до формы контакта

### ISSUE THREAD

**Issue by tsvetkovamaria** [AlexandraFetisova/html-group_8-homework_34_alexandra#9]
### Баг ###
При открытии страницы страница прокручивается до блока формы. 

### Шаги воспроизведения, наблюдаемое поведение: ###
Открыть страницу index.html в браузере Chrome. Увидеть, что при открытии страницы происходит прокрутка до блока формы. http://prntscr.com/ek4eht 

### Ожидаемое поведение: ###
Открыть страницу index.html в браузере Chrome. Увидеть, что при открытии страницы не происходит прокрутка, увидеть блок шапки с блоком промо на первом экране. 

### Решение: ###
Выяснить, почему происходит прокрутка. Если не выясните самостоятельно, спросите в общем чате группы.

**Comment by AlexandraFetisova** [comment]
Данный баг был починен, спросила у наших умных мальчиков, ошибка была в том что в  email 
 был автофокус на 103 строчке кода, удалила его и все стало открываться правильно.
